name: Display meta details in report 
on:
  workflow_dispatch:
  merge_group:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Cache Node Modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: |
          node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Cache Playwright Binaries
      id: cache-playwright
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        key: playwright-${{ hashFiles('package-lock.json') }}

    - name: Set GITHUB_CONTEXT as environment variable
      run: echo "GITHUB_CONTEXT=$(echo '${{ toJson(github) }}')" >> $GITHUB_ENV

    - name: Install dependencies
      id: install-dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci

    - name: Install Playwright Browsers
      id: install-playwright-browsers
      if: steps.cache-playwright.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: |
          npx playwright test  -g '@basic'

    - name: Setup Pages
      uses: actions/configure-pages@v5  

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "./playwright-report"
  
  deploy:
    needs: test
    permissions: 
      pages: writes
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
